### PR TITLE
fix: lock when accessing internal map

### LINKED ISSUE #4481: Node terminated with panic
Happened multiple times that the orchestrator node died with panic even though no job was processing at that time

Sample logs
[panic.md](https://github.com/user-attachments/files/17062438/panic.md)

### PR DESCRIPTION
**Pull request by frrist**
- fixes #4481

### CODE REVIEW

**Review by udsamani — APPROVED** [review]

File: pkg/lib/collections/hashed_priority_queue.go [hunk 1]
```diff
@@ -27,6 +27,8 @@ func NewHashedPriorityQueue[K comparable, T any](indexer IndexerFunc[K, T]) *Has
 // Contains will return true if the provided identifier (of type K)
 // will be found in this queue, false if it is not present.
 func (q *HashedPriorityQueue[K, T]) Contains(id K) bool {
+	q.mu.Lock()
+	defer q.mu.Unlock()
 	_, ok := q.identifiers[id]
```
Comment (wdbaruni) [inline pkg/lib/collections/hashed_priority_queue.go:32]: should we use `RWMutex`?

**Review by wdbaruni — APPROVED** [review]
Approved, but we should switch to `RWMutex`

File: pkg/lib/collections/hashed_priority_queue.go (hunk 1 above)
Comment (frrist) [reply pkg/lib/collections/hashed_priority_queue.go]: done.
