### PR TITLE
Fix Python SDK

### LINKED ISSUE #4164: Implement Python SDK for new models and api changes

### PR DESCRIPTION
**Pull request by udsamani**
This PR does the following

- Run `swag fmt` on `pkg/publicapi/orchestrator/` this formats all API comments on endpoints.
- Generate and update the swager `go generate pkg/swaggger/generate.sh`
- Build the apiclient `make build-python-apiclient`
- Fix the SDK meaning all files under `python/bacalhau_sdk`
- Update README.md for `python/` folder.

Github Keywords
close #4164

### CODE REVIEW

File: pkg/swagger/docs.go [hunk 1]
```diff
@@ -1,4 +1,4 @@
-// Code generated by swaggo/swag. DO NOT EDIT
+// Package swagger Code generated by swaggo/swag. DO NOT EDIT
```
Comment (wdbaruni) [inline pkg/swagger/docs.go:1]: I know we just discussed the benefits and potential of generating the swagger definitions manually instead of using swaggo, but looking at this huge file it scares me to manage it manually. Specially that it includes specifications of things like `models.Job` and `models.Executions`. 

Is there a middle ground where the models definitions are auto-generated, but the API specs are manually generated and documented? We don't need to think about this now, but something for later when we decide to improve our clients generation

File: python/bacalhau_sdk/job_store.py [hunk 2]
```diff
@@ -0,0 +1,152 @@
...
+    ApiListJobsResponse as ListJobsResponse,
+)
+from bacalhau_apiclient.models.api_get_job_response import (
+    ApiGetJobResponse as GetJobResponse,
+)
+
+from bacalhau_sdk.config import init_config
+
+
+class JobStore:
```
Comment (wdbaruni) [inline python/bacalhau_sdk/job_store.py:31]: Nice structure of resource based SDKs. Though can we call them `Jobs` similar to our [go sdk](https://github.com/bacalhau-project/bacalhau/blob/main/pkg/publicapi/client/v2/api_jobs.go#L13). `JobStore` is in internal component related to persisting and retrieving job state, and can be confusing here

File: python/bacalhau_sdk/job_store.py [hunk 3]
```diff
@@ -0,0 +1,152 @@
...
+
+        Args:
+            request (PutJobRequest): A request to put a job to bacalhau network. It encapsulates the job model.
+
+        Returns:
+            PutJobResponse: Once job is successful put on bacalhau netowork, this returns the job details.
+        """
+        return self.orchestrator_service.put_job(request)
+
+    def stop(self, job_id: str, reason: str = None) -> StopJobResponse:
```
Comment (wdbaruni) [inline python/bacalhau_sdk/job_store.py:46]: I forgot about the standards in python, but should they be `stop` or `Stop`?

File: python/bacalhau_sdk/api.py [hunk 4]
```diff
@@ -1,121 +1,44 @@
...
-        state_request = StateRequest(
-            client_id=get_client_id(),
-            job_id=job_id,
-        )
-        api_response = api_instance.results(state_request)
-    except ApiException as e:
-        print("Exception when calling JobApi->results: %s\n" % e)
-    return api_response
+    """Return Job Results"""
+    return orchestrator_service.job_results(id=job_id)
```
Comment (wdbaruni) [inline python/bacalhau_sdk/api.py:34]: can we just delete all these legacy methods? I really don't want to maintain this code if we don't need to, sepially that we broke `submit`, which is the most important one

File: scripts/generate_swagger.sh [hunk 5]
```diff
@@ -2,6 +2,7 @@
 PATH_TO_PROJECT_ROOT=$(git rev-parse --show-toplevel)
 SWAGGER_DIR="${PATH_TO_PROJECT_ROOT}/pkg/swagger"
 PUBLIC_PATH="${PATH_TO_PROJECT_ROOT}/webui/public/swagger"
+DOCS_PATH="${PATH_TO_PROJECT_ROOT}/docs"
```
Comment (wdbaruni) [inline scripts/generate_swagger.sh:5]: can we revisit the structure of these directories? I really don't understand why we are involving `webui` in this. I think it was a wrong decision at some point and I would like to see if we can avoid that

Also does it doesn't make sense to have the swagger generation code under `/pkg/swagger` as `/pkg` should only include code related to bacalhau and not for external tooling

**Review by wdbaruni — COMMENTED** [review]
LGTM. Just minor comments

File: python/bacalhau_sdk/job_store.py (hunk 3 above)
Comment (udsamani) [reply python/bacalhau_sdk/job_store.py:46]: Python is snake case so `stop`.

File: scripts/generate_swagger.sh (hunk 5 above)
Comment (udsamani) [reply scripts/generate_swagger.sh:5]: Makes sense. I am creating an issue to fix it in V2 SDK. #4200 .

File: clients/python/README.md [hunk 6]
```diff
@@ -3,8 +3,8 @@ This page is the reference of the Bacalhau REST API. Project docs are available
 
 This Python package is automatically generated by the [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) project:
 
-- API version: ${PYPI_VERSION}
-- Package version: 0.3.24.dev8
+- API version: ${VERSION}
+- Package version:
```
[the remark this answers is not in the document]
Comment (udsamani) [reply clients/python/README.md:7]: It will be same as our git version. 

https://github.com/bacalhau-project/bacalhau/blob/main/scripts/get_current_version_for_builds.py

This is the script that gets used.

**Review by wdbaruni — APPROVED** [review]
