### PR TITLE
fix: remove system.Environment type

### LINKED ISSUE #4523: Unexpected Log output when running `serve`
```shell
$ bacalhau serve --compute --orchestrator
{"level":"trace","time":"2024-09-24T16:22:54-07:00","message":"BACALHAU_ENVIRONMENT is not set to a known value: "}
{"level":"debug","time":"2024-09-24T16:22:54-07:00","message":"Defaulting to production environment: \n os.Args: [./bin/linux/amd64/bacalhau serve --compute --orchestrator]"}
16:22:54.198 | INF cmd/cli/serve/serve.go:101 > Config loaded from: [], and with data-dir /home/frrist/.bacalhau
16:22:54.199 | INF pkg/repo/fs.go:91 > Initializing repo at /home/frrist/.bacalhau
16:22:54.199 | INF cmd/cli/serve/serve.go:145 > persisted node name n-9bca891a-249b-4614-8fac-d72b096607d9
16:22:54.261 | INF cmd/cli/serve/serve.go:227 > Starting bacalhau...
16:22:54.447 | INF cmd/cli/serve/serve.go:298 > bacalhau node running [address:127.0.0.1:1234] [capacity:"{CPU: 22.4, Memory: 35 GB, Disk: 1.2 TB, GPU: 1}"] [compute_enabled:true] [engines:["docker","wasm"]] [name:n-9bca891a-249b-4614-8fac-d72b096607d9] [orchestrator_address:0.0.0.0:4222] [orchestrator_enabled:true] [orchestrators:["nats://127.0.0.1:4222"]] [publishers:["noop","local"]] [storages:["urldownload","inline"]] [webui_enabled:false]
```
The first two log lines should not be displayed.

### PR DESCRIPTION
**Pull request by frrist**
- closes #4523

In the future we can use build tags (as we already do now) to modify the type of values we use in testing.

### CODE REVIEW

File: pkg/node/config_defaults.go [hunk 1]
```diff
@@ -113,7 +115,10 @@ var TestRequesterConfig = RequesterConfigParams{
 }
 
 func getRequesterConfigParams() RequesterConfigParams {
-	if system.GetEnvironment() == system.EnvironmentTest {
+	if strings.Contains(os.Args[0], "/_test/") ||
+		strings.HasSuffix(os.Args[0], ".test") ||
+		flag.Lookup("test.v") != nil ||
+		flag.Lookup("test.run") != nil {
 		return TestRequesterConfig
 	}
```
Comment (frrist) [inline pkg/node/config_defaults.go:123]: I moved the logic from `GetEnvironment` to here as this was the only caller of the method.

**Review by wdbaruni — APPROVED** [review]
