### PR TITLE
Fix low cleanup frequency in cache tests

### LINKED ISSUE #3635: Bad timer parameter to cache causes flaky tests
base.go:115: Command to execute: [--api-host 127.0.0.1 --api-port 43619 cancel efc0908a-010a-4bc6-b7d2-eb648e6c9bbb]
panic: non-positive interval for NewTicker

goroutine 489 [running]:
time.NewTicker(0x4000aee738?)
	/usr/local/go/src/time/tick.go:24 +0x110
github.com/bacalhau-project/bacalhau/pkg/cache/basic.(*BasicCache[...]).cleanup(0x3a38b00, 0x4000f4ad80)
	/home/circleci/repo/pkg/cache/basic/cache.go:98 +0x68
created by github.com/bacalhau-project/bacalhau/pkg/cache/basic.NewCache[...]
	/home/circleci/repo/pkg/cache/basic/cache.go:53 +0x24c

### PR DESCRIPTION
**Pull request by rossjones**
ticker was firing too frequently, and occassionally resulting in a too-low duration causing flaky tests.

Fixes #3635

### CODE REVIEW

File: pkg/cache/basic/cache.go [hunk 1]
```diff
@@ -50,6 +52,12 @@ func NewCache[T any](options ...Option) (*BasicCache[T], error) {
 		defaultTTL:       config.defaultTTL,
 	}
 
+	fmt.Println("Cache frequency is", config.cleanupFrequency)
+
```
Comment (simonwo) [inline pkg/cache/basic/cache.go:56]: Probably a debug log message at most.

**Review by simonwo — APPROVED** [review]

File: pkg/cache/basic/cache.go (hunk 1 above)
Comment (rossjones) [reply pkg/cache/basic/cache.go:56]: we should probably add a linter to catch these :(
