### PR TITLE
fix migration, tests for more repo types

### LINKED ISSUE #4389: Repo migration is failing
Migrating repo from 1.4.0 to 1.5.0 is failing with:
```
failed to setup repo: failed to reconcile repo: failed to open repo: failed to migrate repo: rename /Users/walid/.bacalhau/orchestrator_store/jobs.db /Users/walid/.bacalhau/orchestrator_store/state_boltdb.db: no such file or directory
```

### How to reproduce
```
# Start with fresh repo
export BACALHAU_DIR=$(mktemp -d)

# run v1.4.0
→ bacalhau-1.4.0 version
12:25:01.37 | INF pkg/repo/fs.go:99 > Initializing repo at '/var/folders/vz/pk7pk9qx1c5gbktg8nhyl88h0000gn/T/tmp.XpUn1hDbW2' for environment 'production'
 CLIENT  SERVER  UPDATE MESSAGE
 v1.4.0  v1.4.0


# run v1.5.0
→ bacalhau-1.5.0 version
12:25:27.158 | INF pkg/repo/migration.go:46 > Migrating repo from version 3 to 4
Error: failed to setup repo: failed to reconcile repo: failed to open repo: failed to migrate repo: rename /var/folders/vz/pk7pk9qx1c5gbktg8nhyl88h0000gn/T/tmp.XpUn1hDbW2/orchestrator_store/jobs.db /var/folders/vz/pk7pk9qx1c5gbktg8nhyl88h0000gn/T/tmp.XpUn1hDbW2/orchestrator_store/state_boltdb.db: no such file or directory
```

### PR DESCRIPTION
**Pull request by frrist**
- closes #4389

### CODE REVIEW

File: pkg/repo/migrations/v3_4.go [hunk 1]
```diff
@@ -136,6 +137,18 @@ var V3Migration = repo.NewMigration(
...
+				return err
+			} else {
+				// we still need to write a node name to the system_metadata.yaml file.
+				nodeID, err := config.GetNodeID(context.Background(), types.Default.NameProvider)
+				if err != nil {
+					return err
+				}
+				if err := r.WriteNodeName(nodeID); err != nil {
+					return fmt.Errorf("migrating node name: %w", err)
+				}
```
Comment (frrist) [inline pkg/repo/migrations/v3_4.go:151]: In the event the repo being migrated doesn't have a config file - resulting from a command like `bacalhau version`, then we need to create a node name here while migrating here as there isn't one in the config file to read from.

File: pkg/repo/migrations/v3_4.go [hunk 2]
```diff
@@ -149,11 +162,15 @@ func migrateComputeStore(repoPath string, config legacy_types.JobStoreConfig) er
 	if oldExecutionStorePath == "" {
 		oldExecutionStorePath = filepath.Join(oldComputeDir, "executions.db")
 	}
-	newExecutionStorePath := filepath.Join(oldComputeDir, "state_boltdb.db")
-	if err := os.Rename(oldExecutionStorePath, newExecutionStorePath); err != nil {
+	// if a store is present migrate it.
+	if _, err := os.Stat(oldExecutionStorePath); err == nil {
+		newExecutionStorePath := filepath.Join(oldComputeDir, "state_boltdb.db")
+		if err := os.Rename(oldExecutionStorePath, newExecutionStorePath); err != nil {
+			return err
```
Comment (frrist) [inline pkg/repo/migrations/v3_4.go:169]: ensures a store is present before attempting to migrate it.

File: pkg/repo/migrations/v3_4.go [hunk 3]
```diff
@@ -173,11 +190,15 @@ func migrateOrchestratorStore(repoPath string, config legacy_types.JobStoreConfi
...
 		oldJobStorePath = filepath.Join(oldOrchestratorDir, "jobs.db")
 	}
-	newJobStorePath := filepath.Join(oldOrchestratorDir, "state_boltdb.db")
-	if err := os.Rename(oldJobStorePath, newJobStorePath); err != nil {
+	// if a store is present migrate it.
+	if _, err := os.Stat(oldJobStorePath); err == nil {
+		newJobStorePath := filepath.Join(oldOrchestratorDir, "state_boltdb.db")
+		if err := os.Rename(oldJobStorePath, newJobStorePath); err != nil {
+			return err
+		}
```
Comment (frrist) [inline pkg/repo/migrations/v3_4.go:198]: ensures a store is present before attempting to migrate it.

File: pkg/repo/migrations/v3_4_test.go [hunk 4]
```diff
@@ -40,7 +40,8 @@ func TestV3MigrationsTestSuite(t *testing.T) {
 	suite.Run(t, new(V3MigrationsTestSuite))
 }
 
-func (suite *V3MigrationsTestSuite) TestV3MigrationWithDefaultRepo() {
```
Comment (frrist) [inline pkg/repo/migrations/v3_4_test.go:43]: I've increased test coverage for a variety of possible repos:
- repo generated from `bacalhau serve --node-type=requester,compute`
- repo generated from `bacalhau serve --node-type=requester`
- repo generated from `bacalhau serve --node-type=compute`
-  repo generated from `bacalhau version`

File: pkg/config/config.go [hunk 5]
```diff
@@ -249,3 +252,25 @@ func KeyAsEnvVar(key string) string {
 		fmt.Sprintf("%s_%s", environmentVariablePrefix, environmentVariableReplace.Replace(key)),
 	)
 }
+
+func GetNodeID(ctx context.Context, nodeNameProviderType string) (string, error) {
```
Comment (wdbaruni) [inline pkg/config/config.go:256]: nit: better to name it GenerateNodeID to avoid confusing it with getting the actual node name

File: pkg/repo/migrations/v3_4.go [hunk 6]
```diff
@@ -136,6 +137,18 @@ var V3Migration = repo.NewMigration(
 						return err
 					}
 				}
+			} else if !os.IsNotExist(err) {
+				// if there was an error other than the file not existing, abort.
+				return err
+			} else {
+				// we still need to write a node name to the system_metadata.yaml file.
+				nodeID, err := config.GetNodeID(context.Background(), types.Default.NameProvider)
```
Comment (wdbaruni) [inline pkg/repo/migrations/v3_4.go:145]: We shouldn't assign a new node name while migrating. If the repo doesn't have a node name, then we shouldn't assign one during migration. It should be treated the same as starting a node with empty or partial repo, right?

Comment (frrist) [reply pkg/repo/migrations/v3_4.go]: I have moved this logic to the `serve` command and will create a node name if one isn't present when the node starts.

File: pkg/repo/fs.go [hunk 7]
```diff
@@ -94,14 +90,6 @@ func (fsr *FsRepo) Init(cfg types.Bacalhau) error {
...
 	log.Info().Msgf("Initializing repo at %s", fsr.path)
 
-	// if it takes longer than 5 seconds to get the node name from a provider, fail
-	nameCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
-	defer cancel()
-	nodeName, err := getNodeID(nameCtx, cfg.NameProvider)
-	if err != nil {
-		return err
-	}
-
```
Comment (frrist) [inline pkg/repo/fs.go:104]: since a node name is only needed by the `serve` command I have removed this code, it's now only done in `cmd/cli/serve.go`

**Review by wdbaruni — APPROVED** [review]
