### PR TITLE
Bugfix: invalid wasm memory request

### LINKED ISSUE #2988: Wasm crash with invalid page limit
The [original report](https://bacalhauproject.slack.com/archives/C052BAZJVEU/p1699076868497019) came in mixed with output from another job, so this has been rebuilt.

```
panic: memoryLimitPages invalid: 13107200 > 65536

goroutine 153030 [running]:
tetratelabs/wazero.(*runtimeConfig).WithMemoryLimitPages(0xc000999540, 0xc80000)
        tetratelabs/wazero@v1.5.0/config.go:263 +0x105
pkg/executor/wasm.(*Executor).Start(0xc0008d2c20, {0x34b4768, 0xc0023c5530}, 0xc0018a6aa0)
        pkg/executor/wasm/executor.go:85 +0xce7
pkg/compute.(*BaseExecutor).Start(0xc00221e0a0, {0x34b4768, 0xc0023c5530}, 0xc0025bce00)
        pkg/compute/executor.go:247 +0x61a
pkg/compute.(*BaseExecutor).Run(0xc00221e0a0, {0x34b4730, 0xc0023c54d0}, {0xc0025bce00, {0xc000a5d020, 0x2e}, 0x2, 0x2, {0x1d88e8b5, 0xedcce355b, ...}, ...})
        pkg/compute/executor.go:292 +0x472
pkg/compute.(*ExecutorBuffer).doRun.func1()
        pkg/compute/executor_buffer.go:139 +0xb6
created by pkg/compute.(*ExecutorBuffer).doRun
        pkg/compute/executor_buffer.go:138 +0x274
```

It looks like the issue is the calculation at https://github.com/bacalhau-project/bacalhau/blob/main/pkg/executor/wasm/executor.go#L82-L86 but attempts to trigger the same behaviour without the invocation went nowhere on 1.1.3

Have asked for replication steps.

### PR DESCRIPTION
**Pull request by Nasfame**
Resolves #2988
Dups #2991 

This PR intends to fail wasm bacalhau jobs that request for RAM>4GB. Currently its panicking

### CODE REVIEW

File: pkg/executor/wasm/executor.go [hunk 1]
```diff
@@ -80,9 +91,13 @@ func (e *Executor) Start(ctx context.Context, request *executor.RunCommandReques
 	// limit is not specified as a multiple of that.
 	engineConfig := wazero.NewRuntimeConfig().WithCloseOnContextDone(true)
 	if request.Resources.Memory > 0 {
-		const pageSize = 65536
-		pageLimit := request.Resources.Memory/pageSize + math.Min(request.Resources.Memory%pageSize, 1)
-		engineConfig = engineConfig.WithMemoryLimitPages(uint32(pageLimit))
+		requestedPages := request.Resources.Memory/WASM_PAGE_SIZE + math.Min(request.Resources.Memory%WASM_PAGE_SIZE, 1)
+		if requestedPages > WASM_MAX_PAGES_LIMIT {
+			err := fmt.Errorf("requested memory exceeds maximum limit: %d > %d", requestedPages, WASM_MAX_PAGES_LIMIT)
```
Comment (Nasfame) [inline pkg/executor/wasm/executor.go:96]: @rossjones the error being returned is correct, but hard to understand for an average error. Should we consider returning error like "Requested memory exceeds the wasm limit - %d > 4GB"

Comment (rossjones) [reply pkg/executor/wasm/executor.go:96]: Yes, that would be a better error message.

Comment (Nasfame) [reply pkg/executor/wasm/executor.go:96]: ok Some BDD tests, cool!

Comment (Nasfame) [reply pkg/executor/wasm/executor.go]: @rossjones i have updated the error msg. But just to be clear do u have a specific wasm program in mind?

Comment (Nasfame) [reply pkg/executor/wasm/executor.go]: I meant for the tests. And how should i add it, can we afford git-lfs?

Comment (Nasfame) [reply pkg/executor/wasm/executor.go]: For now, i can write a unit test by leveraging `NewExecutor()`

**Review by Nasfame — COMMENTED** [review]
@rossjones wrote failing unit test

File: pkg/executor/wasm/executor.go [hunk 2]
```diff
@@ -70,19 +81,23 @@ func (e *Executor) Start(ctx context.Context, request *executor.RunCommandReques
...
+		requestedPages := request.Resources.Memory/WASM_PAGE_SIZE + math.Min(request.Resources.Memory%WASM_PAGE_SIZE, 1)
+		if requestedPages > WASM_MAX_PAGES_LIMIT {
+			err = fmt.Errorf("requested memory exceeds the wasm limit - %d > 4GB", request.Resources.Memory)
+			log.Err(err).Msgf("requested memory exceeds maximum limit: %d > %d", requestedPages, WASM_MAX_PAGES_LIMIT)
+			return err
+		}
+		engineConfig = engineConfig.WithMemoryLimitPages(uint32(requestedPages))
+	}
+
+	engineParams, err := wasmmodels.DecodeArguments(request.EngineParams)
```
Comment (Nasfame) [inline pkg/executor/wasm/executor.go:98]: i had to reorder cuz my test was failing due to decoding wasm. Additionally it made more sense to check mem config first.

File: pkg/executor/wasm/executor_test.go [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+}
+
+func (m *mockExecutor) Get(executionID string) (*mockHandler, bool) {
+	args := m.Called(executionID)
+	return args.Get(0).(*mockHandler), args.Bool(1)
+}
+
+func (m *mockExecutor) Put(executionID string, handler *mockHandler) {
+	_ = m.Called(executionID, handler)
+}
```
Comment (rossjones) [inline pkg/executor/wasm/executor_test.go:40]: Is this used anywhere?

File: pkg/executor/wasm/executor_test.go [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+
+func TestFailingRequestedMemGreaterThan4GB(t *testing.T) {
+	e, err := NewExecutor()
+
+	assert.Nil(t, err)
```
Comment (rossjones) [inline pkg/executor/wasm/executor_test.go:45]: Rather than assert, most of our tests use `t.Require().*`. So in this case `t.Require().NoError(err)`

File: pkg/executor/wasm/executor_test.go [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+		Resources:   resources,
+		EngineParams: &models.SpecConfig{
+			Type:   models.EngineWasm,
+			Params: map[string]any{},
+		},
+	}
+
+	err = e.Start(context.Background(), r)
+
+	assert.NotNil(t, err)
```
Comment (rossjones) [inline pkg/executor/wasm/executor_test.go:68]: `t.Require().Error(err)`

File: pkg/executor/wasm/executor_test.go
Comment (rossjones) [inline pkg/executor/wasm/executor_test.go:1]: The linter complained that

```
Test files missing '//go:build integration || !unit' or '//go:build unit || !integration':
./pkg/executor/wasm/executor_test.go
```

So `//go:build unit || !integration` needs to be the first line in any test file. Can use !unit || integration when we want integration tests. But for now just adding `//go:build unit || !integration` would appease the linter.

**Review by rossjones — CHANGES_REQUESTED** [review]
Looking good, definitely heading in the right direction.  A couple of comments on use of assert, and a linting problem.

File: pkg/executor/wasm/executor_test.go (hunk 3 above)
Comment (Nasfame) [reply pkg/executor/wasm/executor_test.go:40]: ah forgot to remove it my bad @rossjones

File: pkg/executor/wasm/executor_test.go (hunk 4 above)
Comment (Nasfame) [reply pkg/executor/wasm/executor_test.go:45]: okay, quite new to both

Comment (Nasfame) [reply pkg/executor/wasm/executor_test.go:16]: @rossjones i just checked, the `t.Require()` is not present in testing.T

Comment (Nasfame) [reply pkg/executor/wasm/executor_test.go:16]: also `assert.Nil` is used in the codebase

File: pkg/executor/wasm/executor_test.go
Comment (Nasfame) [reply pkg/executor/wasm/executor_test.go:1]: Not sure whether this fall on either side - "unit" or "integration". To me its both leaning slightly on **integration**. 

It is a BDD test

File: pkg/executor/wasm/executor_test.go (hunk 3 above)
Comment (Nasfame) [reply pkg/executor/wasm/executor_test.go]: removed

File: pkg/executor/wasm/executor_test.go
Comment (rossjones) [reply pkg/executor/wasm/executor_test.go:1]: Integration tests are normally end-to-end, so this is definitely a unit test.

File: pkg/executor/wasm/executor_test.go (hunk 4 above)
Comment (Nasfame) [reply pkg/executor/wasm/executor_test.go:18]: looks more like `unittest` in python. Not sure if its really necessary for BD test. but sure i ill make the changes

File: pkg/executor/wasm/executor_test.go
Comment (Nasfame) [reply pkg/executor/wasm/executor_test.go:1]: Agree to disagree.I have made the changes

File: pkg/executor/wasm/executor_test.go (hunk 4 above)
Comment (Nasfame) [reply pkg/executor/wasm/executor_test.go]: Done

Comment (Nasfame) [reply pkg/executor/wasm/executor_test.go]: I get it s.Require does assert.Error not nil and t.FailNow(). Make sense

File: pkg/executor/wasm/executor.go [hunk 6]
```diff
@@ -57,8 +57,19 @@ func (*Executor) ShouldBidBasedOnUsage(
...
+// Wazero: is compliant to WebAssembly Core Specification 1.0 and 2.0.
+//
+// WebAssembly1:  linear memory objects have sizes measured in pages. Each page is 65536 (2^16) bytes.
+// In WebAssembly version 1, a linear memory can have at most 65536 pages, for a total of 2^32 bytes (4 gibibytes).
+
+const WASM_ARCH = 32
+const WASM_PAGE_SIZE = 1 << (WASM_ARCH / 2)
+const WASM_MAX_PAGES_LIMIT = 1 << (WASM_ARCH / 2)
+
+// TODO: wait for support for wasm64 in wazero
```
Comment (rossjones) [inline pkg/executor/wasm/executor.go:69]:
```suggestion
```

Comment (Nasfame) [reply pkg/executor/wasm/executor.go]: done

**Comment by Nasfame** [comment]
@rossjones the CI is failing but passing locally: Can u check?

```
GOROOT=/Users/hiro/.go/go1.20.7 #gosetup
GOPATH=/Users/hiro/go #gosetup
/Users/hiro/.go/go1.20.7/bin/go test -c -o /Users/hiro/Library/Caches/JetBrains/GoLand2023.2/tmp/GoLand/___TestScenarios_in_github_com_bacalhau_project_bacalhau_pkg_test_executor.test github.com/bacalhau-project/bacalhau/pkg/test/executor #gosetup
/Users/hiro/.go/go1.20.7/bin/go tool test2json -t /Users/hiro/Library/Caches/JetBrains/GoLand2023.2/tmp/GoLand/___TestScenarios_in_github_com_bacalhau_project_bacalhau_pkg_test_executor.test -test.v -test.paniconexit0 -test.run ^\QTestScenarios\E$
=== RUN   TestScenarios
--- PASS: TestScenarios (33.92s)
=== RUN   TestScenarios/cat_file_to_stdout
    scenario_test.go:17: cat_file_to_stdout
    setup.go:47: creating repo for testing at: /var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734408162438000
01:56:48.162 | INF pkg/repo/fs.go:208 > Initializing repo at '/var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734408162438000' for environment 'local'
01:56:48.688 | INF pkg/compute/capacity/system/provider.go:86 > cannot inspect system GPUs: nvidia-smi not installed. GPUs will not be used.
01:56:48.688 | INF pkg/devstack/devstack.go:91 > Starting Devstack [Config:{"AllowListedLocalPaths":[],"BadComputeActors":0,"BadRequesterActors":0,"CPUProfilingFile":"","ComputeOnlyNodes":0,"DisabledFeatures":"{[] [] []}","ExecutorPlugins":false,"HybridNodes":1,"MemoryProfilingFile":"","NodeInfoPublisherInterval":"{0s 0s 0s}","Peer":"","PublicIPFSMode":false,"RequesterOnlyNodes":0}]
01:56:49.329 | INF pkg/compute/store/boltdb/store.go:86 > creating new bbolt database [NodeID:QmWHZkWY]
01:56:49.344 | INF pkg/compute/logstream/network.go:33 > Selected address for logstreams [Address:/ip4/192.168.42.8/tcp/50284] [NodeID:QmWHZkWY]
01:56:49.344 | WRN pkg/version/update.go:95 > Update frequency is zero or less so no update checks will run [NodeID:QmWHZkWY] [Update.CheckFrequency:0]
01:56:49.501 | INF pkg/executor/wasm/executor.go:167 > waiting on execution [executionID:3c6242d7-5f6b-4c13-855d-ac36c0f0a6ac]
01:56:49.501 | INF pkg/executor/wasm/handler.go:103 > instantiating wasm modules [entrypoint:_start] [execution:3c6242d7-5f6b-4c13-855d-ac36c0f0a6ac] [job:test-job]
01:56:49.513 | INF pkg/executor/wasm/handler.go:147 > running execution [entrypoint:_start] [execution:3c6242d7-5f6b-4c13-855d-ac36c0f0a6ac] [job:test-job]
01:56:49.513 | INF pkg/executor/wasm/handler.go:163 > execution ended [entrypoint:_start] [execution:3c6242d7-5f6b-4c13-855d-ac36c0f0a6ac] [exit_code:0] [job:test-job]
01:56:49.517 | INF pkg/executor/wasm/executor.go:177 > received results from execution [executionID:3c6242d7-5f6b-4c13-855d-ac36c0f0a6ac]
01:56:49.517 | INF pkg/compute/executor.go:183 > cleaning up execution [execution:3c6242d7-5f6b-4c13-855d-ac36c0f0a6ac]
01:56:49.518 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-job-info
01:56:49.518 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-node-info
    --- PASS: TestScenarios/cat_file_to_stdout (1.36s)
=== RUN   TestScenarios/awk_file
    scenario_test.go:17: awk_file
    setup.go:47: creating repo for testing at: /var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734409543167000
01:56:49.543 | INF pkg/repo/fs.go:208 > Initializing repo at '/var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734409543167000' for environment 'local'
01:56:49.821 | INF pkg/compute/capacity/system/provider.go:86 > cannot inspect system GPUs: nvidia-smi not installed. GPUs will not be used.
01:56:49.821 | INF pkg/devstack/devstack.go:91 > Starting Devstack [Config:{"AllowListedLocalPaths":[],"BadComputeActors":0,"BadRequesterActors":0,"CPUProfilingFile":"","ComputeOnlyNodes":0,"DisabledFeatures":"{[] [] []}","ExecutorPlugins":false,"HybridNodes":1,"MemoryProfilingFile":"","NodeInfoPublisherInterval":"{0s 0s 0s}","Peer":"","PublicIPFSMode":false,"RequesterOnlyNodes":0}]
01:56:50.44 | INF pkg/compute/store/boltdb/store.go:86 > creating new bbolt database [NodeID:QmebG4Z8]
01:56:50.457 | INF pkg/compute/logstream/network.go:33 > Selected address for logstreams [Address:/ip4/192.168.42.8/tcp/50292] [NodeID:QmebG4Z8]
01:56:50.457 | WRN pkg/version/update.go:95 > Update frequency is zero or less so no update checks will run [NodeID:QmebG4Z8] [Update.CheckFrequency:0]
01:56:50.624 | INF pkg/executor/docker/executor.go:113 > starting execution [executionID:983faeb1-d46b-4e22-874f-08a4157a7ace] [jobID:test-job]
01:57:10.815 | INF pkg/executor/docker/executor.go:204 > waiting on execution [executionID:983faeb1-d46b-4e22-874f-08a4157a7ace]
01:57:10.815 | INF pkg/executor/docker/handler.go:64 > starting container execution [container:fca8d8c5fbc3d8bde72c3785742decba06e47d9f08dc65d45408817185a36a09] [execution:983faeb1-d46b-4e22-874f-08a4157a7ace] [job:test-job]
01:57:11.007 | INF pkg/executor/docker/handler.go:113 > received status from container [container:fca8d8c5fbc3d8bde72c3785742decba06e47d9f08dc65d45408817185a36a09] [execution:983faeb1-d46b-4e22-874f-08a4157a7ace] [job:test-job] [status:0]
01:57:11.015 | INF pkg/executor/docker/handler.go:138 > captured stdout/stderr for container [container:fca8d8c5fbc3d8bde72c3785742decba06e47d9f08dc65d45408817185a36a09] [execution:983faeb1-d46b-4e22-874f-08a4157a7ace] [job:test-job]
01:57:11.017 | INF pkg/executor/docker/handler.go:146 > container execution ended [container:fca8d8c5fbc3d8bde72c3785742decba06e47d9f08dc65d45408817185a36a09] [execution:983faeb1-d46b-4e22-874f-08a4157a7ace] [job:test-job] [status:0]
01:57:11.018 | INF pkg/executor/docker/handler.go:160 > destroying the container [container:fca8d8c5fbc3d8bde72c3785742decba06e47d9f08dc65d45408817185a36a09] [execution:983faeb1-d46b-4e22-874f-08a4157a7ace] [job:test-job]
01:57:11.018 | INF pkg/executor/docker/handler.go:152 > killing the container [container:fca8d8c5fbc3d8bde72c3785742decba06e47d9f08dc65d45408817185a36a09] [execution:983faeb1-d46b-4e22-874f-08a4157a7ace] [job:test-job]
01:57:11.02 | INF pkg/executor/docker/handler.go:169 > removing container [container:fca8d8c5fbc3d8bde72c3785742decba06e47d9f08dc65d45408817185a36a09] [execution:983faeb1-d46b-4e22-874f-08a4157a7ace] [job:test-job]
01:57:11.05 | INF pkg/executor/docker/executor.go:214 > received results from execution [executionID:983faeb1-d46b-4e22-874f-08a4157a7ace]
01:57:11.05 | INF pkg/compute/executor.go:183 > cleaning up execution [execution:983faeb1-d46b-4e22-874f-08a4157a7ace]
01:57:11.052 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-job-info
01:57:11.052 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-node-info
    --- PASS: TestScenarios/awk_file (21.55s)
=== RUN   TestScenarios/logtest
    scenario_test.go:17: logtest
    setup.go:47: creating repo for testing at: /var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734431067175000
01:57:11.067 | INF pkg/repo/fs.go:208 > Initializing repo at '/var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734431067175000' for environment 'local'
01:57:11.531 | INF pkg/compute/capacity/system/provider.go:86 > cannot inspect system GPUs: nvidia-smi not installed. GPUs will not be used.
01:57:11.531 | INF pkg/devstack/devstack.go:91 > Starting Devstack [Config:{"AllowListedLocalPaths":[],"BadComputeActors":0,"BadRequesterActors":0,"CPUProfilingFile":"","ComputeOnlyNodes":0,"DisabledFeatures":"{[] [] []}","ExecutorPlugins":false,"HybridNodes":1,"MemoryProfilingFile":"","NodeInfoPublisherInterval":"{0s 0s 0s}","Peer":"","PublicIPFSMode":false,"RequesterOnlyNodes":0}]
01:57:12.207 | INF pkg/compute/store/boltdb/store.go:86 > creating new bbolt database [NodeID:QmcPCVsX]
01:57:12.222 | INF pkg/compute/logstream/network.go:33 > Selected address for logstreams [Address:/ip4/192.168.42.8/tcp/50317] [NodeID:QmcPCVsX]
01:57:12.222 | WRN pkg/version/update.go:95 > Update frequency is zero or less so no update checks will run [NodeID:QmcPCVsX] [Update.CheckFrequency:0]
01:57:12.398 | INF pkg/executor/wasm/executor.go:167 > waiting on execution [executionID:4d6b0aa5-729c-4472-bbff-e92503d0a95a]
01:57:12.398 | INF pkg/executor/wasm/handler.go:103 > instantiating wasm modules [entrypoint:_start] [execution:4d6b0aa5-729c-4472-bbff-e92503d0a95a] [job:test-job]
01:57:12.41 | INF pkg/executor/wasm/handler.go:147 > running execution [entrypoint:_start] [execution:4d6b0aa5-729c-4472-bbff-e92503d0a95a] [job:test-job]
01:57:12.425 | INF pkg/executor/wasm/handler.go:163 > execution ended [entrypoint:_start] [execution:4d6b0aa5-729c-4472-bbff-e92503d0a95a] [exit_code:0] [job:test-job]
01:57:12.524 | INF pkg/executor/wasm/executor.go:177 > received results from execution [executionID:4d6b0aa5-729c-4472-bbff-e92503d0a95a]
01:57:12.525 | INF pkg/compute/executor.go:183 > cleaning up execution [execution:4d6b0aa5-729c-4472-bbff-e92503d0a95a]
01:57:12.526 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-job-info
01:57:12.526 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-node-info
    --- PASS: TestScenarios/logtest (1.46s)
=== RUN   TestScenarios/wasm_hello_world
    scenario_test.go:17: wasm_hello_world
    setup.go:47: creating repo for testing at: /var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734432531590000
01:57:12.531 | INF pkg/repo/fs.go:208 > Initializing repo at '/var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734432531590000' for environment 'local'
01:57:12.757 | INF pkg/compute/capacity/system/provider.go:86 > cannot inspect system GPUs: nvidia-smi not installed. GPUs will not be used.
01:57:12.757 | INF pkg/devstack/devstack.go:91 > Starting Devstack [Config:{"AllowListedLocalPaths":[],"BadComputeActors":0,"BadRequesterActors":0,"CPUProfilingFile":"","ComputeOnlyNodes":0,"DisabledFeatures":"{[] [] []}","ExecutorPlugins":false,"HybridNodes":1,"MemoryProfilingFile":"","NodeInfoPublisherInterval":"{0s 0s 0s}","Peer":"","PublicIPFSMode":false,"RequesterOnlyNodes":0}]
01:57:13.151 | INF pkg/compute/store/boltdb/store.go:86 > creating new bbolt database [NodeID:QmZNgHKB]
01:57:13.174 | INF pkg/compute/logstream/network.go:33 > Selected address for logstreams [Address:/ip4/192.168.42.8/tcp/50321] [NodeID:QmZNgHKB]
01:57:13.174 | WRN pkg/version/update.go:95 > Update frequency is zero or less so no update checks will run [NodeID:QmZNgHKB] [Update.CheckFrequency:0]
01:57:13.284 | INF pkg/executor/wasm/executor.go:167 > waiting on execution [executionID:b3338459-c16c-41c7-99e6-cd3c4a84b614]
01:57:13.284 | INF pkg/executor/wasm/handler.go:103 > instantiating wasm modules [entrypoint:_start] [execution:b3338459-c16c-41c7-99e6-cd3c4a84b614] [job:test-job]
01:57:13.293 | INF pkg/executor/wasm/handler.go:147 > running execution [entrypoint:_start] [execution:b3338459-c16c-41c7-99e6-cd3c4a84b614] [job:test-job]
01:57:13.293 | INF pkg/executor/wasm/handler.go:163 > execution ended [entrypoint:_start] [execution:b3338459-c16c-41c7-99e6-cd3c4a84b614] [exit_code:0] [job:test-job]
01:57:13.298 | INF pkg/executor/wasm/executor.go:177 > received results from execution [executionID:b3338459-c16c-41c7-99e6-cd3c4a84b614]
01:57:13.298 | INF pkg/compute/executor.go:183 > cleaning up execution [execution:b3338459-c16c-41c7-99e6-cd3c4a84b614]
01:57:13.299 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-job-info
01:57:13.299 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-node-info
    --- PASS: TestScenarios/wasm_hello_world (0.78s)
=== RUN   TestScenarios/wasm_dynamic_link
    scenario_test.go:17: wasm_dynamic_link
    setup.go:47: creating repo for testing at: /var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734433308600000
01:57:13.308 | INF pkg/repo/fs.go:208 > Initializing repo at '/var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734433308600000' for environment 'local'
01:57:13.609 | INF pkg/compute/capacity/system/provider.go:86 > cannot inspect system GPUs: nvidia-smi not installed. GPUs will not be used.
01:57:13.609 | INF pkg/devstack/devstack.go:91 > Starting Devstack [Config:{"AllowListedLocalPaths":[],"BadComputeActors":0,"BadRequesterActors":0,"CPUProfilingFile":"","ComputeOnlyNodes":0,"DisabledFeatures":"{[] [] []}","ExecutorPlugins":false,"HybridNodes":1,"MemoryProfilingFile":"","NodeInfoPublisherInterval":"{0s 0s 0s}","Peer":"","PublicIPFSMode":false,"RequesterOnlyNodes":0}]
01:57:13.997 | INF pkg/compute/store/boltdb/store.go:86 > creating new bbolt database [NodeID:QmQwKsjn]
01:57:14.01 | INF pkg/compute/logstream/network.go:33 > Selected address for logstreams [Address:/ip4/192.168.42.8/tcp/50326] [NodeID:QmQwKsjn]
01:57:14.011 | WRN pkg/version/update.go:95 > Update frequency is zero or less so no update checks will run [NodeID:QmQwKsjn] [Update.CheckFrequency:0]
01:57:14.164 | INF pkg/executor/wasm/executor.go:167 > waiting on execution [executionID:40edc85f-fb35-4dd0-9452-72114fbdb115]
01:57:14.164 | INF pkg/executor/wasm/handler.go:103 > instantiating wasm modules [entrypoint:_start] [execution:40edc85f-fb35-4dd0-9452-72114fbdb115] [job:test-job]
01:57:14.173 | INF pkg/executor/wasm/handler.go:147 > running execution [entrypoint:_start] [execution:40edc85f-fb35-4dd0-9452-72114fbdb115] [job:test-job]
01:57:14.178 | INF pkg/executor/wasm/executor.go:177 > received results from execution [executionID:40edc85f-fb35-4dd0-9452-72114fbdb115]
01:57:14.178 | INF pkg/compute/executor.go:183 > cleaning up execution [execution:40edc85f-fb35-4dd0-9452-72114fbdb115]
01:57:14.179 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-job-info
01:57:14.179 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-node-info
    --- PASS: TestScenarios/wasm_dynamic_link (0.88s)
=== RUN   TestScenarios/cat_file_to_volume
    scenario_test.go:17: cat_file_to_volume
    setup.go:47: creating repo for testing at: /var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734434204934000
01:57:14.205 | INF pkg/repo/fs.go:208 > Initializing repo at '/var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734434204934000' for environment 'local'
01:57:14.458 | INF pkg/compute/capacity/system/provider.go:86 > cannot inspect system GPUs: nvidia-smi not installed. GPUs will not be used.
01:57:14.458 | INF pkg/devstack/devstack.go:91 > Starting Devstack [Config:{"AllowListedLocalPaths":[],"BadComputeActors":0,"BadRequesterActors":0,"CPUProfilingFile":"","ComputeOnlyNodes":0,"DisabledFeatures":"{[] [] []}","ExecutorPlugins":false,"HybridNodes":1,"MemoryProfilingFile":"","NodeInfoPublisherInterval":"{0s 0s 0s}","Peer":"","PublicIPFSMode":false,"RequesterOnlyNodes":0}]
01:57:15.102 | INF pkg/compute/store/boltdb/store.go:86 > creating new bbolt database [NodeID:QmTqX91y]
01:57:15.116 | INF pkg/compute/logstream/network.go:33 > Selected address for logstreams [Address:/ip4/192.168.42.8/tcp/50330] [NodeID:QmTqX91y]
01:57:15.116 | WRN pkg/version/update.go:95 > Update frequency is zero or less so no update checks will run [NodeID:QmTqX91y] [Update.CheckFrequency:0]
01:57:15.297 | INF pkg/executor/docker/executor.go:113 > starting execution [executionID:90bc8378-f82b-40c4-95b8-c0e32771e0ba] [jobID:test-job]
01:57:15.37 | INF pkg/executor/docker/handler.go:64 > starting container execution [container:0745319ec721679fce280208fd59ef1e2f6161572efe2020b96f2f2cce3b101b] [execution:90bc8378-f82b-40c4-95b8-c0e32771e0ba] [job:test-job]
01:57:15.37 | INF pkg/executor/docker/executor.go:204 > waiting on execution [executionID:90bc8378-f82b-40c4-95b8-c0e32771e0ba]
01:57:15.536 | INF pkg/executor/docker/handler.go:113 > received status from container [container:0745319ec721679fce280208fd59ef1e2f6161572efe2020b96f2f2cce3b101b] [execution:90bc8378-f82b-40c4-95b8-c0e32771e0ba] [job:test-job] [status:0]
01:57:15.545 | INF pkg/executor/docker/handler.go:138 > captured stdout/stderr for container [container:0745319ec721679fce280208fd59ef1e2f6161572efe2020b96f2f2cce3b101b] [execution:90bc8378-f82b-40c4-95b8-c0e32771e0ba] [job:test-job]
01:57:15.546 | INF pkg/executor/docker/handler.go:146 > container execution ended [container:0745319ec721679fce280208fd59ef1e2f6161572efe2020b96f2f2cce3b101b] [execution:90bc8378-f82b-40c4-95b8-c0e32771e0ba] [job:test-job] [status:0]
01:57:15.546 | INF pkg/executor/docker/handler.go:160 > destroying the container [container:0745319ec721679fce280208fd59ef1e2f6161572efe2020b96f2f2cce3b101b] [execution:90bc8378-f82b-40c4-95b8-c0e32771e0ba] [job:test-job]
01:57:15.546 | INF pkg/executor/docker/handler.go:152 > killing the container [container:0745319ec721679fce280208fd59ef1e2f6161572efe2020b96f2f2cce3b101b] [execution:90bc8378-f82b-40c4-95b8-c0e32771e0ba] [job:test-job]
01:57:15.55 | INF pkg/executor/docker/handler.go:169 > removing container [container:0745319ec721679fce280208fd59ef1e2f6161572efe2020b96f2f2cce3b101b] [execution:90bc8378-f82b-40c4-95b8-c0e32771e0ba] [job:test-job]
01:57:15.565 | INF pkg/executor/docker/executor.go:214 > received results from execution [executionID:90bc8378-f82b-40c4-95b8-c0e32771e0ba]
01:57:15.565 | INF pkg/compute/executor.go:183 > cleaning up execution [execution:90bc8378-f82b-40c4-95b8-c0e32771e0ba]
01:57:15.566 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-job-info
01:57:15.566 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-node-info
    --- PASS: TestScenarios/cat_file_to_volume (1.39s)
=== RUN   TestScenarios/grep_file
    scenario_test.go:17: grep_file
    setup.go:47: creating repo for testing at: /var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734435588818000
01:57:15.589 | INF pkg/repo/fs.go:208 > Initializing repo at '/var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734435588818000' for environment 'local'
01:57:16.028 | INF pkg/compute/capacity/system/provider.go:86 > cannot inspect system GPUs: nvidia-smi not installed. GPUs will not be used.
01:57:16.028 | INF pkg/devstack/devstack.go:91 > Starting Devstack [Config:{"AllowListedLocalPaths":[],"BadComputeActors":0,"BadRequesterActors":0,"CPUProfilingFile":"","ComputeOnlyNodes":0,"DisabledFeatures":"{[] [] []}","ExecutorPlugins":false,"HybridNodes":1,"MemoryProfilingFile":"","NodeInfoPublisherInterval":"{0s 0s 0s}","Peer":"","PublicIPFSMode":false,"RequesterOnlyNodes":0}]
01:57:16.391 | INF pkg/compute/store/boltdb/store.go:86 > creating new bbolt database [NodeID:QmS9GqKY]
01:57:16.407 | INF pkg/compute/logstream/network.go:33 > Selected address for logstreams [Address:/ip4/192.168.42.8/tcp/50335] [NodeID:QmS9GqKY]
01:57:16.407 | WRN pkg/version/update.go:95 > Update frequency is zero or less so no update checks will run [NodeID:QmS9GqKY] [Update.CheckFrequency:0]
01:57:16.571 | INF pkg/executor/docker/executor.go:113 > starting execution [executionID:415304ff-4547-496d-9d07-039413a82e30] [jobID:test-job]
01:57:16.595 | INF pkg/executor/docker/executor.go:204 > waiting on execution [executionID:415304ff-4547-496d-9d07-039413a82e30]
01:57:16.595 | INF pkg/executor/docker/handler.go:64 > starting container execution [container:3ed7d940e35f27385366b45ac7297dbf133e2b4d1c5fce40a150821ce25bb5fe] [execution:415304ff-4547-496d-9d07-039413a82e30] [job:test-job]
01:57:16.717 | INF pkg/executor/docker/handler.go:113 > received status from container [container:3ed7d940e35f27385366b45ac7297dbf133e2b4d1c5fce40a150821ce25bb5fe] [execution:415304ff-4547-496d-9d07-039413a82e30] [job:test-job] [status:0]
01:57:16.724 | INF pkg/executor/docker/handler.go:138 > captured stdout/stderr for container [container:3ed7d940e35f27385366b45ac7297dbf133e2b4d1c5fce40a150821ce25bb5fe] [execution:415304ff-4547-496d-9d07-039413a82e30] [job:test-job]
01:57:16.724 | INF pkg/executor/docker/handler.go:146 > container execution ended [container:3ed7d940e35f27385366b45ac7297dbf133e2b4d1c5fce40a150821ce25bb5fe] [execution:415304ff-4547-496d-9d07-039413a82e30] [job:test-job] [status:0]
01:57:16.724 | INF pkg/executor/docker/handler.go:160 > destroying the container [container:3ed7d940e35f27385366b45ac7297dbf133e2b4d1c5fce40a150821ce25bb5fe] [execution:415304ff-4547-496d-9d07-039413a82e30] [job:test-job]
01:57:16.724 | INF pkg/executor/docker/handler.go:152 > killing the container [container:3ed7d940e35f27385366b45ac7297dbf133e2b4d1c5fce40a150821ce25bb5fe] [execution:415304ff-4547-496d-9d07-039413a82e30] [job:test-job]
01:57:16.729 | INF pkg/executor/docker/handler.go:169 > removing container [container:3ed7d940e35f27385366b45ac7297dbf133e2b4d1c5fce40a150821ce25bb5fe] [execution:415304ff-4547-496d-9d07-039413a82e30] [job:test-job]
01:57:16.743 | INF pkg/executor/docker/executor.go:214 > received results from execution [executionID:415304ff-4547-496d-9d07-039413a82e30]
01:57:16.744 | INF pkg/compute/executor.go:183 > cleaning up execution [execution:415304ff-4547-496d-9d07-039413a82e30]
01:57:16.749 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-job-info
01:57:16.75 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-node-info
    --- PASS: TestScenarios/grep_file (1.18s)
=== RUN   TestScenarios/sed_file
    scenario_test.go:17: sed_file
    setup.go:47: creating repo for testing at: /var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734436772963000
01:57:16.773 | INF pkg/repo/fs.go:208 > Initializing repo at '/var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734436772963000' for environment 'local'
01:57:17.171 | INF pkg/compute/capacity/system/provider.go:86 > cannot inspect system GPUs: nvidia-smi not installed. GPUs will not be used.
01:57:17.172 | INF pkg/devstack/devstack.go:91 > Starting Devstack [Config:{"AllowListedLocalPaths":[],"BadComputeActors":0,"BadRequesterActors":0,"CPUProfilingFile":"","ComputeOnlyNodes":0,"DisabledFeatures":"{[] [] []}","ExecutorPlugins":false,"HybridNodes":1,"MemoryProfilingFile":"","NodeInfoPublisherInterval":"{0s 0s 0s}","Peer":"","PublicIPFSMode":false,"RequesterOnlyNodes":0}]
01:57:18.027 | INF pkg/compute/store/boltdb/store.go:86 > creating new bbolt database [NodeID:QmYz5fVP]
01:57:18.044 | INF pkg/compute/logstream/network.go:33 > Selected address for logstreams [Address:/ip4/192.168.42.8/tcp/50342] [NodeID:QmYz5fVP]
01:57:18.044 | WRN pkg/version/update.go:95 > Update frequency is zero or less so no update checks will run [NodeID:QmYz5fVP] [Update.CheckFrequency:0]
01:57:18.212 | INF pkg/executor/docker/executor.go:113 > starting execution [executionID:4dbb9372-a3da-491d-9e50-8826c1006586] [jobID:test-job]
01:57:18.463 | INF pkg/executor/docker/handler.go:64 > starting container execution [container:dbf845079e3a25808b20dce58175213309025a37c1184aba190f0469d5eb8b5c] [execution:4dbb9372-a3da-491d-9e50-8826c1006586] [job:test-job]
01:57:18.463 | INF pkg/executor/docker/executor.go:204 > waiting on execution [executionID:4dbb9372-a3da-491d-9e50-8826c1006586]
01:57:18.648 | INF pkg/executor/docker/handler.go:113 > received status from container [container:dbf845079e3a25808b20dce58175213309025a37c1184aba190f0469d5eb8b5c] [execution:4dbb9372-a3da-491d-9e50-8826c1006586] [job:test-job] [status:0]
01:57:18.656 | INF pkg/executor/docker/handler.go:138 > captured stdout/stderr for container [container:dbf845079e3a25808b20dce58175213309025a37c1184aba190f0469d5eb8b5c] [execution:4dbb9372-a3da-491d-9e50-8826c1006586] [job:test-job]
01:57:18.658 | INF pkg/executor/docker/handler.go:146 > container execution ended [container:dbf845079e3a25808b20dce58175213309025a37c1184aba190f0469d5eb8b5c] [execution:4dbb9372-a3da-491d-9e50-8826c1006586] [job:test-job] [status:0]
01:57:18.658 | INF pkg/executor/docker/handler.go:160 > destroying the container [container:dbf845079e3a25808b20dce58175213309025a37c1184aba190f0469d5eb8b5c] [execution:4dbb9372-a3da-491d-9e50-8826c1006586] [job:test-job]
01:57:18.658 | INF pkg/executor/docker/handler.go:152 > killing the container [container:dbf845079e3a25808b20dce58175213309025a37c1184aba190f0469d5eb8b5c] [execution:4dbb9372-a3da-491d-9e50-8826c1006586] [job:test-job]
01:57:18.663 | INF pkg/executor/docker/handler.go:169 > removing container [container:dbf845079e3a25808b20dce58175213309025a37c1184aba190f0469d5eb8b5c] [execution:4dbb9372-a3da-491d-9e50-8826c1006586] [job:test-job]
01:57:18.702 | INF pkg/executor/docker/executor.go:214 > received results from execution [executionID:4dbb9372-a3da-491d-9e50-8826c1006586]
01:57:18.702 | INF pkg/compute/executor.go:183 > cleaning up execution [execution:4dbb9372-a3da-491d-9e50-8826c1006586]
01:57:18.703 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-job-info
01:57:18.703 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-node-info
    --- PASS: TestScenarios/sed_file (1.97s)
=== RUN   TestScenarios/wasm_env_vars
    scenario_test.go:17: wasm_env_vars
    setup.go:47: creating repo for testing at: /var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734438721454000
01:57:18.721 | INF pkg/repo/fs.go:208 > Initializing repo at '/var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734438721454000' for environment 'local'
01:57:19.257 | INF pkg/compute/capacity/system/provider.go:86 > cannot inspect system GPUs: nvidia-smi not installed. GPUs will not be used.
01:57:19.257 | INF pkg/devstack/devstack.go:91 > Starting Devstack [Config:{"AllowListedLocalPaths":[],"BadComputeActors":0,"BadRequesterActors":0,"CPUProfilingFile":"","ComputeOnlyNodes":0,"DisabledFeatures":"{[] [] []}","ExecutorPlugins":false,"HybridNodes":1,"MemoryProfilingFile":"","NodeInfoPublisherInterval":"{0s 0s 0s}","Peer":"","PublicIPFSMode":false,"RequesterOnlyNodes":0}]
01:57:19.766 | INF pkg/compute/store/boltdb/store.go:86 > creating new bbolt database [NodeID:QmQKG15d]
01:57:19.781 | INF pkg/compute/logstream/network.go:33 > Selected address for logstreams [Address:/ip4/192.168.42.8/tcp/50349] [NodeID:QmQKG15d]
01:57:19.781 | WRN pkg/version/update.go:95 > Update frequency is zero or less so no update checks will run [NodeID:QmQKG15d] [Update.CheckFrequency:0]
01:57:19.89 | INF pkg/executor/wasm/executor.go:167 > waiting on execution [executionID:45cca1f8-ddcc-463e-9b0c-74f1fbd5dd9d]
01:57:19.89 | INF pkg/executor/wasm/handler.go:103 > instantiating wasm modules [entrypoint:_start] [execution:45cca1f8-ddcc-463e-9b0c-74f1fbd5dd9d] [job:test-job]
01:57:19.901 | INF pkg/executor/wasm/handler.go:147 > running execution [entrypoint:_start] [execution:45cca1f8-ddcc-463e-9b0c-74f1fbd5dd9d] [job:test-job]
01:57:19.906 | INF pkg/executor/wasm/executor.go:177 > received results from execution [executionID:45cca1f8-ddcc-463e-9b0c-74f1fbd5dd9d]
01:57:19.906 | INF pkg/compute/executor.go:183 > cleaning up execution [execution:45cca1f8-ddcc-463e-9b0c-74f1fbd5dd9d]
01:57:19.907 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-job-info
01:57:19.907 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-node-info
    --- PASS: TestScenarios/wasm_env_vars (1.19s)
=== RUN   TestScenarios/wasm_csv_transform
    scenario_test.go:17: wasm_csv_transform
    setup.go:47: creating repo for testing at: /var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734439914529000
01:57:19.914 | INF pkg/repo/fs.go:208 > Initializing repo at '/var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734439914529000' for environment 'local'
01:57:20.093 | INF pkg/compute/capacity/system/provider.go:86 > cannot inspect system GPUs: nvidia-smi not installed. GPUs will not be used.
01:57:20.093 | INF pkg/devstack/devstack.go:91 > Starting Devstack [Config:{"AllowListedLocalPaths":[],"BadComputeActors":0,"BadRequesterActors":0,"CPUProfilingFile":"","ComputeOnlyNodes":0,"DisabledFeatures":"{[] [] []}","ExecutorPlugins":false,"HybridNodes":1,"MemoryProfilingFile":"","NodeInfoPublisherInterval":"{0s 0s 0s}","Peer":"","PublicIPFSMode":false,"RequesterOnlyNodes":0}]
01:57:20.881 | INF pkg/compute/store/boltdb/store.go:86 > creating new bbolt database [NodeID:QmSDpkxw]
01:57:20.898 | INF pkg/compute/logstream/network.go:33 > Selected address for logstreams [Address:/ip4/192.168.42.8/tcp/50353] [NodeID:QmSDpkxw]
01:57:20.899 | WRN pkg/version/update.go:95 > Update frequency is zero or less so no update checks will run [NodeID:QmSDpkxw] [Update.CheckFrequency:0]
01:57:21.07 | INF pkg/executor/wasm/executor.go:167 > waiting on execution [executionID:c5d8ac5e-fb77-4b05-bd24-218becef3139]
01:57:21.07 | INF pkg/executor/wasm/handler.go:103 > instantiating wasm modules [entrypoint:_start] [execution:c5d8ac5e-fb77-4b05-bd24-218becef3139] [job:test-job]
01:57:21.088 | INF pkg/executor/wasm/handler.go:147 > running execution [entrypoint:_start] [execution:c5d8ac5e-fb77-4b05-bd24-218becef3139] [job:test-job]
01:57:21.094 | INF pkg/executor/wasm/handler.go:163 > execution ended [entrypoint:_start] [execution:c5d8ac5e-fb77-4b05-bd24-218becef3139] [exit_code:0] [job:test-job]
01:57:21.098 | INF pkg/executor/wasm/executor.go:177 > received results from execution [executionID:c5d8ac5e-fb77-4b05-bd24-218becef3139]
01:57:21.099 | INF pkg/compute/executor.go:183 > cleaning up execution [execution:c5d8ac5e-fb77-4b05-bd24-218becef3139]
01:57:21.1 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-job-info
01:57:21.101 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-node-info
    --- PASS: TestScenarios/wasm_csv_transform (1.19s)
=== RUN   TestScenarios/wasm_exit_code
    scenario_test.go:17: wasm_exit_code
    setup.go:47: creating repo for testing at: /var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734441104159000
01:57:21.104 | INF pkg/repo/fs.go:208 > Initializing repo at '/var/folders/44/nbbyll_10jd0z8rj_qxm43740000gn/T/1699734441104159000' for environment 'local'
01:57:21.649 | INF pkg/compute/capacity/system/provider.go:86 > cannot inspect system GPUs: nvidia-smi not installed. GPUs will not be used.
01:57:21.649 | INF pkg/devstack/devstack.go:91 > Starting Devstack [Config:{"AllowListedLocalPaths":[],"BadComputeActors":0,"BadRequesterActors":0,"CPUProfilingFile":"","ComputeOnlyNodes":0,"DisabledFeatures":"{[] [] []}","ExecutorPlugins":false,"HybridNodes":1,"MemoryProfilingFile":"","NodeInfoPublisherInterval":"{0s 0s 0s}","Peer":"","PublicIPFSMode":false,"RequesterOnlyNodes":0}]
01:57:21.934 | INF pkg/compute/store/boltdb/store.go:86 > creating new bbolt database [NodeID:QmNVuzyh]
01:57:21.95 | INF pkg/compute/logstream/network.go:33 > Selected address for logstreams [Address:/ip4/192.168.42.8/tcp/50359] [NodeID:QmNVuzyh]
01:57:21.95 | WRN pkg/version/update.go:95 > Update frequency is zero or less so no update checks will run [NodeID:QmNVuzyh] [Update.CheckFrequency:0]
01:57:22.059 | INF pkg/executor/wasm/executor.go:167 > waiting on execution [executionID:0e9af790-cfb4-45e7-8ce0-5b98f8664b19]
01:57:22.059 | INF pkg/executor/wasm/handler.go:103 > instantiating wasm modules [entrypoint:_start] [execution:0e9af790-cfb4-45e7-8ce0-5b98f8664b19] [job:test-job]
01:57:22.068 | INF pkg/executor/wasm/handler.go:147 > running execution [entrypoint:_start] [execution:0e9af790-cfb4-45e7-8ce0-5b98f8664b19] [job:test-job]
01:57:22.068 | INF pkg/executor/wasm/handler.go:163 > execution ended [entrypoint:_start] [execution:0e9af790-cfb4-45e7-8ce0-5b98f8664b19] [exit_code:5] [job:test-job]
01:57:22.073 | INF pkg/executor/wasm/executor.go:177 > received results from execution [executionID:0e9af790-cfb4-45e7-8ce0-5b98f8664b19]
01:57:22.073 | INF pkg/compute/executor.go:183 > cleaning up execution [execution:0e9af790-cfb4-45e7-8ce0-5b98f8664b19]
01:57:22.074 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-job-info
01:57:22.074 | INF pkg/pubsub/libp2p/pubsub.go:138 > done closing libp2p pubsub for topic bacalhau-node-info
    --- PASS: TestScenarios/wasm_exit_code (0.98s)
PASS

```

File: pkg/executor/wasm/executor.go [hunk 7]
```diff
@@ -57,8 +57,17 @@ func (*Executor) ShouldBidBasedOnUsage(
 	return resource.NewChainedResourceBidStrategy().ShouldBidBasedOnUsage(ctx, request, usage)
 }
 
+// Wazero: is compliant to WebAssembly Core Specification 1.0 and 2.0.
+//
+// WebAssembly1:  linear memory objects have sizes measured in pages. Each page is 65536 (2^16) bytes.
+// In WebAssembly version 1, a linear memory can have at most 65536 pages, for a total of 2^32 bytes (4 gibibytes).
+
+const WASM_ARCH = 32
+const WASM_PAGE_SIZE = 1 << (WASM_ARCH / 2)
```
Comment (rossjones) [inline pkg/executor/wasm/executor.go:66]: I'm not sure this is based on the arch size, it's entirely possible they'll stick with 65536 in wasm64, so we should go with 65536 for now.

File: pkg/executor/wasm/executor.go [hunk 8]
```diff
@@ -57,8 +57,17 @@ func (*Executor) ShouldBidBasedOnUsage(
...
+const WASM_MAX_PAGES_LIMIT = 1 << (WASM_ARCH / 2)
+
 // Start initiates an execution based on the provided RunCommandRequest.
-func (e *Executor) Start(ctx context.Context, request *executor.RunCommandRequest) error {
+func (e *Executor) Start(ctx context.Context, request *executor.RunCommandRequest) (err error) {
```
Comment (rossjones) [inline pkg/executor/wasm/executor.go:70]:
```suggestion
func (e *Executor) Start(ctx context.Context, request *executor.RunCommandRequest) (error) {
```

**Comment by rossjones** [comment]
@Nasfame couple of minor changes, and then need to update the branch and I think it's good to go.

File: pkg/executor/wasm/executor.go (hunk 8 above)
Comment (Nasfame) [reply pkg/executor/wasm/executor.go:68]: got to make change manually as the var is referenced in the code without declaration

File: pkg/executor/wasm/executor.go (hunk 7 above)
Comment (Nasfame) [reply pkg/executor/wasm/executor.go:64]: image

65536 seemed like magic number to me, so that's why put it up.

Comment (rossjones) [reply pkg/executor/wasm/executor.go:64]: I agree, so we can put it into a const as 65536, but it's in the spec and so we should invent ways to generate the number if it isn't necessary.

Comment (Nasfame) [reply pkg/executor/wasm/executor.go:64]: WASM_ARCH isn't really a magic number per say, it implies 32 bit arch. But i get ur point, sure the doc would do

Comment (rossjones) [reply pkg/executor/wasm/executor.go]: FWIW, it was only the PAGE_SIZE I meant, calculating the limit was fine, but don't change it now we can fix it up when wasm64 arrives.  In the meantime, need to figure out this apparently python error in CircleCI.

**Comment by rossjones** [comment]
@Nasfame It looks like CI is failing with the Python build, and the reason is that you've added a tag to one of the commits that doesn't follow semver so the tags causes a problem.  I think if you remove the tag then it should run to completion and be ready for merging.

File: pkg/executor/wasm/executor.go (hunk 7 above)
Comment (Nasfame) [reply pkg/executor/wasm/executor.go]: @rossjones i don't mind fixing it. done

**Review by simonwo — APPROVED** [review]

**Comment by Nasfame** [comment]
> @Nasfame It looks like CI is failing with the Python build, and the reason is that you've added a tag to one of the commits that doesn't follow semver so the tag causes a problem. This is because we use the tag name as a version in various python configs. I think if you remove the tag then it should run to completion and be ready for merging.

@rossjones ack

File: pkg/executor/wasm/executor.go [hunk 9]
```diff
@@ -68,19 +77,23 @@ func (e *Executor) Start(ctx context.Context, request *executor.RunCommandReques
...
 	if request.Resources.Memory > 0 {
-		const pageSize = 65536
-		pageLimit := request.Resources.Memory/pageSize + math.Min(request.Resources.Memory%pageSize, 1)
-		engineConfig = engineConfig.WithMemoryLimitPages(uint32(pageLimit))
+		requestedPages := request.Resources.Memory/WASM_PAGE_SIZE + math.Min(request.Resources.Memory%WASM_PAGE_SIZE, 1)
+		if requestedPages > WASM_MAX_PAGES_LIMIT {
+			err := fmt.Errorf("requested memory exceeds the wasm limit - %d > 4GB", request.Resources.Memory)
+			log.Err(err).Msgf("requested memory exceeds maximum limit: %d > %d", requestedPages, WASM_MAX_PAGES_LIMIT)
+			return err
+		}
```
[the remark this answers is not in the document]
Comment (Nasfame) [reply pkg/executor/wasm/executor.go:90]: The limits are imposed by external runtime i.e wasm. So we need to do checks here to prevent panics by wazero. But yes we can implement this limits ourselves in the bid strategy as well effectively short circuiting the job at bid stage.
