### PR TITLE
Transport log cmd errors to the client in main message struct

### LINKED ISSUE #2668: Bacalhau logs websocket error when clientid does not match job
When I try to look at the logs I get the following error. It did work one time on a bacalhau job and has not worked since.

```bacalhau logs -f 472734f4-4615-40ec-8670-1c1ff41e0202```
```failed to read: websocket: close 1006 (abnormal closure): unexpected EOF%```

Note this is pointing towards our requester node, which requires running the following to test directly

export BACALHAU_API_HOST=54.210.19.52

### LINKED ISSUE #2669: `bacalhau logs` panics (always?)
```
% go run . logs --simon 
panic: unable to redefine 'h' shorthand in "logs" flagset: it's already used for "history" flag

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0x140019bff00, 0x140019cd860)
        /Users/simon/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:874 +0x354
github.com/spf13/pflag.(*FlagSet).VarPF(0x14001315b98?, {0x107425a80, 0x140018bdc6e}, {0x106372ea5, 0x4}, {0x106bf1de0, 0x1}, {0x140018bdc61, 0xd})
        /Users/simon/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:831 +0x148
github.com/spf13/pflag.(*FlagSet).BoolVarP(0x106f649a0?, 0x1063a5306?, {0x106372ea5?, 0x1063a573e?}, {0x106bf1de0?, 0x1?}, 0x1?, {0x140018bdc61?, 0x0?})
        /Users/simon/go/pkg/mod/github.com/spf13/pflag@v1.0.5/bool.go:55 +0x48
github.com/spf13/pflag.(*FlagSet).BoolP(...)
        /Users/simon/go/pkg/mod/github.com/spf13/pflag@v1.0.5/bool.go:80
github.com/spf13/cobra.(*Command).InitDefaultHelpFlag(0x1?)
        /Users/simon/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1148 +0x10c
github.com/spf13/cobra.(*Command).execute(0x140019afb00, {0x1400196b490, 0x1, 0x1})
        /Users/simon/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:858 +0xb0
github.com/spf13/cobra.(*Command).ExecuteC(0x1400198fb00)
        /Users/simon/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/simon/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/bacalhau-project/bacalhau/cmd/cli.Execute()
        /Users/simon/bacalhau/cmd/cli/root.go:196 +0x334
main.main()
        /Users/simon/bacalhau/main.go:37 +0x140
```

Something to do with it trying to automatically generate a help flag when the usage is printed.

### PR DESCRIPTION
**Pull request by rossjones**
Currently messages are sent via the control channel, and this runs up against an unclearly documented limit of 125 bytes for the control channel message.  This means that all errors end up as abnormal errors at the client end, something we should never send ourselves.

Now errors are included in the message structure, if present it is printed to STDERR and the process is cancelled.

No changes to access policy have been made yet.

Resolves  #2669

### CODE REVIEW

File: cmd/cli/logs/logs.go [hunk 1]
```diff
@@ -49,10 +49,5 @@ func NewCmd() *cobra.Command {
 		`Follow the logs in real-time after retrieving the current logs.`,
 	)
 
-	logsCmd.PersistentFlags().BoolVarP(
-		&options.Follow, "history", "h", false,
-		`Show all logs with history. TODO better definition`,
-	)
-
```
Comment (simonwo) [inline cmd/cli/logs/logs.go:56]: Should the `WithHistory` option be present/doing anything?

**Review by simonwo — APPROVED** [review]
I'd rather we keep the original error issue open for now until we've made a decision about access control?

File: cmd/cli/logs/logs.go (hunk 1 above)
Comment (rossjones) [reply cmd/cli/logs/logs.go:56]: The intent was that by default we show everything so far, and then optionally follow. This was intended to allow you to just follow from the current output but I think we changed our mind on it quite late.

I've got a couple of other cleanups to do in logging so I'll do them in separate PRs.
